version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - /var/www/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true